### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by pangxiang** [deepch/RTSPtoWebRTC#160]
Multigoroutines will cause panic "fatal error: concurrent map read and map write".

fatal error: concurrent map read and map write

goroutine 5120 [running]:
runtime.throw(0xc75dd9, 0x21)
	/usr/lib/golang/src/runtime/panic.go:1116 +0x72 fp=0xc000b51b88 sp=0xc000b51b58 pc=0x437772
runtime.mapaccess1_faststr(0xb88260, 0xc0003b2750, 0xc0322d5d80, 0x20, 0xf)
	/usr/lib/golang/src/runtime/map_faststr.go:21 +0x465 fp=0xc000b51bf8 sp=0xc000b51b88 pc=0x415505
main.(*ConfigST).cast(0xc000259c80, 0xc0322d5d80, 0x20, 0x0, 0xf4240, 0x239673cecfc0, 0x2625a00, 0xc00b449500, 0x2934, 0x2a80)
	/opt/goProject/rtsptowebrtc/config.go:157 +0xa9 fp=0xc000b51ce0 sp=0xc000b51bf8 pc=0xae9d49
main.RTSPWorker(0xc0322d5d80, 0x20, 0xc00fda4e80, 0x39, 0x0, 0x0, 0x0)
	/opt/goProject/rtsptowebrtc/stream.go:97 +0x49c fp=0xc000b51ec8 sp=0xc000b51ce0 pc=0xaee57c
main.RTSPWorkerLoop(0xc0322d5d80, 0x20, 0xc00fda4e80, 0x39, 0xc032000000)
	/opt/goProject/rtsptowebrtc/stream.go:33 +0x199 fp=0xc000b51fb8 sp=0xc000b51ec8 pc=0xaede99
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000b51fc0 sp=0xc000b51fb8 pc=0x46ce81
created by main.(*ConfigST).addStreams
	/opt/goProject/rtsptowebrtc/http.go:66 +0x25d

goroutine 1 [chan receive, 34 minutes]:
main.main()
	/opt/goProject/rtsptowebrtc/main.go:21 +0x165

goroutine 20 [IO wait, 4 minutes]:
internal/poll.runtime_pollWait(0x7f5729203a98, 0x72, 0x0)
	/usr/lib/golang/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00042a018, 0x72, 0x0, 0x0, 0xc61687)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00042a000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_unix.go:394 +0x1fc
net.(*netFD).accept(0xc00042a000, 0x868d45e28923b8af, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc00041e100, 0x622efbcc, 0xc000211d30, 0x4c9306)
	/usr/lib/golang/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00041e100, 0xc000211d80, 0x18, 0xc000183500, 0x6f5e2c)
	/usr/lib/golang/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc000424000, 0xd51940, 0xc00041e100, 0x0, 0x0)
	/usr/lib/golang/src/net/http/server.go:2937 +0x266
net/http.(*Server).ListenAndServe(0xc000424000, 0xc000424000, 0xc000211f10)
	/usr/lib/golang/src/net/http/server.go:2866 +0xb7
net/http.ListenAndServe(...)
	/usr/lib/golang/src/net/http/server.go:3120
github.com/gin-gonic/gin.(*Engine).Run(0xc000140000, 0xc000211fa0, 0x1, 0x1, 0x0, 0x0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:301 +0x14a
main.serveHTTP()
	/opt/goProject/rtsptowebrtc/http.go:38 +0x2dd
created by main.main
	/opt/goProject/rtsptowebrtc/main.go:11 +0x39

goroutine 22 [syscall, 34 minutes]:
os/signal.signal_recv(0x0)
	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/lib/golang/src/os/signal/signal.go:150 +0x45

goroutine 23 [chan receive, 34 minutes]:
main.main.func1(0xc0001b9860, 0xc0002c0770)
	/opt/goProject/rtsptowebrtc/main.go:16 +0x45
created by main.main
	/opt/goProject/rtsptowebrtc/main.go:15 +0x10b

goroutine 36 [select]:
main.RTSPWorker(0xc0004182c0, 0x20, 0xc00047e030, 0x29, 0x0, 0x0, 0x0)
	/opt/goProject/rtsptowebrtc/stream.go:71 +0x2e5
main.RTSPWorkerLoop(0xc0004182c0, 0x20, 0xc00047e030, 0x29, 0xc000000000)
	/opt/goProject/rtsptowebrtc/stream.go:33 +0x199
created by main.(*ConfigST).addStreams
	/opt/goProject/rtsptowebrtc/http.go:66 +0x25d

goroutine 84504 [select]:
github.com/pion/transport/packetio.(*Buffer).Read(0xc02ff98660, 0xc032044c00, 0x5b4, 0x5b4, 0x0, 0x0, 0x30)
	/root/go/pkg/mod/github.com/pion/transport@v0.12.2/packetio/buffer.go:266 +0x145
github.com/pion/srtp/v2.(*ReadStreamSRTP).Read(...)
	/root/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/stream_srtp.go:76
github.com/pion/webrtc/v3.(*RTPReceiver).streamsForSSRC.func1(0xc032044c00, 0x5b4, 0x5b4, 0x0, 0x0, 0x0, 0x0, 0xc039bcd920)
	/root/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.5/rtpreceiver.go:305 +0x52
github.com/pion/interceptor.RTPReaderFunc.Read(0xc0188b91e0, 0xc032044c00, 0x5b4, 0x5b4, 0x0, 0x6, 0x6, 0x418ce5, 0x40f365)
	/root/go/pkg/mod/github.com/pion/interceptor@v0.0.9/interceptor.go:87 +0x4e
github.com/pion/interceptor/pkg/nack.(*GeneratorInterceptor).BindRemoteStream.func1(0xc032044c00, 0x5b4, 0x5b4, 0x0, 0xc029aad2c0, 0x0, 0xc054e00401, 0xc025940001)
	/root/go/pkg/mod/github.com/pion/interceptor@v0.0.9/pkg/nack/generator_interceptor.go:84 +0x7e
github.com/pion/interceptor.RTPReaderFunc.Read(0xc02ebe9e80, 0xc032044c00, 0x5b4, 0x5b4, 0x0, 0x0, 0x5, 0xc02594ee08, 0x2)
	/root/go/pkg/mod/github.com/pion/interceptor@v0.0.9/interceptor.go:87 +0x4e
github.com/pion/webrtc/v3.(*RTPReceiver).readRTP(0xc06147aa80, 0xc032044c00, 0x5b4, 0x5b4, 0xc061f7ec60, 0x40f130, 0x0, 0x40f130, 0x448f9f)
	/root/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.5/rtpreceiver.go:259 +0x17d
github.com/pion/webrtc/v3.(*TrackRemote).Read(0xc061f7ec60, 0xc032044c00, 0x5b4, 0x5b4, 0xc02cfd5340, 0x1, 0x1, 0xc02594edf0)
	/root/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.5/track_remote.go:123 +0xa5
github.com/pion/webrtc/v3.(*TrackRemote).peek(0xc061f7ec60, 0xc032044c00, 0x5b4, 0x5b4, 0x200, 0x200, 0xc03e7debc0, 0x40889a)
	/root/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.5/track_remote.go:163 +0x56
github.com/pion/webrtc/v3.(*TrackRemote).determinePayloadType(0xc061f7ec60, 0x0, 0x0)
	/root/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.5/track_remote.go:145 +0x9e
github.com/pion/webrtc/v3.(*PeerConnection).startReceiver.func1(0xc06147aa80, 0xc0516c6540)
	/root/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.5/peerconnection.go:1158 +0x53
created by github.com/pion/webrtc/v3.(*PeerConnection).startReceiver
	/root/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.5/peerconnection.go:1157 +0x285

goroutine 147 [select]:
main.RTSPWorker(0xc0006a4080, 0x20, 0xc0006ae030, 0x29, 0x0, 0x0, 0x0)
	/opt/goProject/rtsptowebrtc/stream.go:71 +0x2e5

**Comment by czk630597526** [comment]
map里加锁，这个map不是sync.map，同时读写会崩溃
